payment_gateway:
    resource: "@PaymentGatewayBundle/Controller/"
    type:     annotation
    prefix:   /

default:
    resource: "@DefaultBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"
